### ISSUE TITLE
button color works incorrectly

### ISSUE THREAD

**Issue by rafiip** [mayuce/LottieAlertDialog#3]
in galaxy s5 , the button color is set to the background of button and not to the button itself. a picture is attached.
![image](https://user-images.githubusercontent.com/13455772/56084486-b93dc480-5e48-11e9-94e7-98492555a366.png)

**Comment by mayuce** [comment]
Can you share your alert dialog builder code snippet ?

**Comment by rafiip** [comment]
here is the code:
```
private void showDialog() {
		new LottieAlertDialog.Builder(this, DialogTypes.TYPE_QUESTION)
				.setTitle("نظرت چیه؟")
				.setDescription("با ثبت نظر مارو حمایت کنین")
				.setPositiveText("نظر میدم")
				.setNoneText("بعدن")
				.setNegativeText("نمیدم")
				.setPositiveTextColor(Color.parseColor("#ffffff"))
				.setNegativeTextColor(getResources().getColor(colorMap.getPrimaryColorRes()))
				.setNoneTextColor(getResources().getColor(colorMap.getPrimaryColorRes()))
				.setPositiveButtonColor(getResources().getColor(colorMap.getPrimaryColorRes()))
				.setPositiveListener(new ClickListener() {
					@Override
					public void onClick(LottieAlertDialog lottieAlertDialog) {

					}
				})
				.setNegativeListener(new ClickListener() {
					@Override
					public void onClick(LottieAlertDialog lottieAlertDialog) {

					}
				})
				.setNoneListener(new ClickListener() {
					@Override
					public void onClick(LottieAlertDialog lottieAlertDialog) {

					}
				})

				.build().show();
		;
	}
```

**Comment by mayuce** [comment]
Can you try giving the colors like below: 
`               .setPositiveButtonColor(Color.parseColor("#f44242"))
                .setPositiveTextColor(Color.parseColor("#ffeaea"))
                .setNegativeButtonColor(Color.parseColor("#ffbb00"))
                .setNegativeTextColor(Color.parseColor("#0a0906"))
                .setNoneButtonColor(Color.parseColor("#1cd3ef"))
                .setNoneTextColor(Color.parseColor("#c407c4"))
`

**Comment by rafiip** [comment]
I am so sorry for my late answer. I got distracted by something else and forget about this issue.
I have used the code you provided. The result is as follows:
![photo_2019-06-17_03-08-36](https://user-images.githubusercontent.com/13455772/59570425-3685ef80-90ad-11e9-8e3b-ea49f47fc4c2.jpg)

**Comment by davidalexissb** [comment]
i have same issue

**Comment by RaviDhoriya** [comment]
@umbracorp @mehraf 
I was able to resolve this issue replacing setColorFilter() by setBackgroundColor in LottieAlertDialog.kt
