### ISSUE TITLE
Why minsdk is 19

### ISSUE THREAD

**Issue by Nikoloutsos** [mayuce/LottieAlertDialog#4]
Airbnb lottie animation requires api level greater than 16.
So why LottieAlertDialog wants minsdk to be higher than 19??

I cannot use it in my project because of that ;/

**Comment by Crdzbird** [comment]
Actually i was searching in the library, and it can perfectly go down to api 16 :)

i will submit a pull request, and let's hope for the best :pray:

**Comment by mayuce** [comment]
Sorry for that guys. Now PR accepted, thanks for the effort @Crdzbird
