### ISSUE TITLE
Add function

### ISSUE THREAD

**Issue by AnthonyPct** [mayuce/LottieAlertDialog#7]
Hello, 
It would be cool if you could add setAnimation("animationName.json") method in the builder. Like that, we could define lottie animations we want. And also add setImageAssetFolder("imageFolderName") method for animations that require images. 

Thanks ;)

**Comment by Crdzbird** [comment]
Actually there's an option to add your own animation.

Change your Lottie Configuration to this...
```
alertDialog = LottieAlertDialog.Builder(context!!, DialogTypes.TYPE_CUSTOM,"your_asset.json")
            .setTitle(getString(R.string.any_value))
            .setDescription(getString(R.string.any_description))
            .build()
        alertDialog.setCancelable(false)
```

**Comment by AnthonyPct** [comment]
Ah ok, i didn't see sorry. But, for now we can't set animations that require image, the app crash because there is no folderName assign to LottieAnimationView

**Comment by Crdzbird** [comment]
For the folder, make sure that every asset is assign to the asset folder, in a future commit there's gonna be an option to add your custom folder :) 
(or you can add it with a pull request :smiley: )
