### ISSUE TITLE
unable to write the file 

### ISSUE THREAD

**Issue by unknown191998** [mayuce/LottieAlertDialog#8]
i want to add more animation but unable to add the condition in lottieAlertDailog.kt showing its read only how can i add custom alert

**Comment by mayuce** [comment]
1. Fork the project 
2. Add your custom alerts to your repository
3. Import your new library to your project 👍🏻

**Comment by mayuce** [comment]
@Crdzbird has added the custom alert feature to project, he can explain how to use it.

**Comment by Crdzbird** [comment]
@unknown191998  for add custom animations.

1. Create your **asset folder**.
2. **Inside** your **asset folder** you must **add** your **CustomAnimationFile.json**
3. Now in the **Lottie Builder** you must **add** your **CustomAnimationFile.json** and also **select the TYPE_CUSTOM** from the **DialogTypes**.
Ex.
`LottieAlertDialog.Builder(context!!, DialogTypes.TYPE_CUSTOM, "registration_success.json")`

**Comment by unknown191998** [comment]
thank you so much mate @Crdzbird  and @mayuce
